server:
  port: 8080

spring:
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/jy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    username: wpf1340701723@163.com
    password: wswpf1340701723
    default-encoding: UTF-8
    port: 465

    properties:
      auth: true
      mail:
        smtp:
          ssl:
            enable: true
        imap:
          ssl:
            socketFactory:
              fallback: false

  redis:
    host: localhost
    port: 6379
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jianyi.bean
logging:
  level:
    com.jianyi.mapper: debug